// NFL team defensive stats — yards allowed per game by position (2024 season)
// Used for grading: higher = weaker defense (OVER signal)
export const TEAM_STATS = {
  ARI: { pass_yds_allowed: 248, rush_yds_allowed: 122, rec_yds_allowed_wr: 165, rec_yds_allowed_te: 68, rec_yds_allowed_rb: 45 },
  ATL: { pass_yds_allowed: 238, rush_yds_allowed: 108, rec_yds_allowed_wr: 158, rec_yds_allowed_te: 62, rec_yds_allowed_rb: 38 },
  BAL: { pass_yds_allowed: 196, rush_yds_allowed: 98,  rec_yds_allowed_wr: 132, rec_yds_allowed_te: 52, rec_yds_allowed_rb: 32 },
  BUF: { pass_yds_allowed: 208, rush_yds_allowed: 105, rec_yds_allowed_wr: 140, rec_yds_allowed_te: 58, rec_yds_allowed_rb: 35 },
  CAR: { pass_yds_allowed: 268, rush_yds_allowed: 135, rec_yds_allowed_wr: 178, rec_yds_allowed_te: 78, rec_yds_allowed_rb: 52 },
  CHI: { pass_yds_allowed: 252, rush_yds_allowed: 118, rec_yds_allowed_wr: 168, rec_yds_allowed_te: 70, rec_yds_allowed_rb: 42 },
  CIN: { pass_yds_allowed: 232, rush_yds_allowed: 112, rec_yds_allowed_wr: 155, rec_yds_allowed_te: 60, rec_yds_allowed_rb: 36 },
  CLE: { pass_yds_allowed: 210, rush_yds_allowed: 102, rec_yds_allowed_wr: 142, rec_yds_allowed_te: 55, rec_yds_allowed_rb: 34 },
  DAL: { pass_yds_allowed: 225, rush_yds_allowed: 110, rec_yds_allowed_wr: 150, rec_yds_allowed_te: 65, rec_yds_allowed_rb: 40 },
  DEN: { pass_yds_allowed: 202, rush_yds_allowed: 100, rec_yds_allowed_wr: 135, rec_yds_allowed_te: 54, rec_yds_allowed_rb: 33 },
  DET: { pass_yds_allowed: 242, rush_yds_allowed: 115, rec_yds_allowed_wr: 162, rec_yds_allowed_te: 66, rec_yds_allowed_rb: 41 },
  GB:  { pass_yds_allowed: 218, rush_yds_allowed: 106, rec_yds_allowed_wr: 146, rec_yds_allowed_te: 60, rec_yds_allowed_rb: 37 },
  HOU: { pass_yds_allowed: 228, rush_yds_allowed: 108, rec_yds_allowed_wr: 152, rec_yds_allowed_te: 63, rec_yds_allowed_rb: 39 },
  IND: { pass_yds_allowed: 235, rush_yds_allowed: 113, rec_yds_allowed_wr: 157, rec_yds_allowed_te: 67, rec_yds_allowed_rb: 42 },
  JAX: { pass_yds_allowed: 258, rush_yds_allowed: 128, rec_yds_allowed_wr: 172, rec_yds_allowed_te: 74, rec_yds_allowed_rb: 48 },
  KC:  { pass_yds_allowed: 198, rush_yds_allowed: 95,  rec_yds_allowed_wr: 133, rec_yds_allowed_te: 50, rec_yds_allowed_rb: 30 },
  LAC: { pass_yds_allowed: 220, rush_yds_allowed: 107, rec_yds_allowed_wr: 148, rec_yds_allowed_te: 61, rec_yds_allowed_rb: 38 },
  LAR: { pass_yds_allowed: 215, rush_yds_allowed: 104, rec_yds_allowed_wr: 145, rec_yds_allowed_te: 58, rec_yds_allowed_rb: 36 },
  LV:  { pass_yds_allowed: 262, rush_yds_allowed: 130, rec_yds_allowed_wr: 175, rec_yds_allowed_te: 76, rec_yds_allowed_rb: 50 },
  MIA: { pass_yds_allowed: 245, rush_yds_allowed: 120, rec_yds_allowed_wr: 164, rec_yds_allowed_te: 69, rec_yds_allowed_rb: 44 },
  MIN: { pass_yds_allowed: 222, rush_yds_allowed: 109, rec_yds_allowed_wr: 149, rec_yds_allowed_te: 62, rec_yds_allowed_rb: 39 },
  NE:  { pass_yds_allowed: 255, rush_yds_allowed: 126, rec_yds_allowed_wr: 170, rec_yds_allowed_te: 73, rec_yds_allowed_rb: 47 },
  NO:  { pass_yds_allowed: 240, rush_yds_allowed: 116, rec_yds_allowed_wr: 160, rec_yds_allowed_te: 65, rec_yds_allowed_rb: 40 },
  NYG: { pass_yds_allowed: 260, rush_yds_allowed: 128, rec_yds_allowed_wr: 173, rec_yds_allowed_te: 75, rec_yds_allowed_rb: 49 },
  NYJ: { pass_yds_allowed: 205, rush_yds_allowed: 99,  rec_yds_allowed_wr: 138, rec_yds_allowed_te: 53, rec_yds_allowed_rb: 32 },
  PHI: { pass_yds_allowed: 200, rush_yds_allowed: 97,  rec_yds_allowed_wr: 134, rec_yds_allowed_te: 51, rec_yds_allowed_rb: 31 },
  PIT: { pass_yds_allowed: 194, rush_yds_allowed: 93,  rec_yds_allowed_wr: 130, rec_yds_allowed_te: 49, rec_yds_allowed_rb: 29 },
  SEA: { pass_yds_allowed: 230, rush_yds_allowed: 111, rec_yds_allowed_wr: 154, rec_yds_allowed_te: 64, rec_yds_allowed_rb: 40 },
  SF:  { pass_yds_allowed: 192, rush_yds_allowed: 91,  rec_yds_allowed_wr: 128, rec_yds_allowed_te: 48, rec_yds_allowed_rb: 28 },
  TB:  { pass_yds_allowed: 236, rush_yds_allowed: 114, rec_yds_allowed_wr: 158, rec_yds_allowed_te: 66, rec_yds_allowed_rb: 41 },
  TEN: { pass_yds_allowed: 256, rush_yds_allowed: 124, rec_yds_allowed_wr: 170, rec_yds_allowed_te: 72, rec_yds_allowed_rb: 46 },
  WAS: { pass_yds_allowed: 234, rush_yds_allowed: 112, rec_yds_allowed_wr: 156, rec_yds_allowed_te: 64, rec_yds_allowed_rb: 39 },
};

// League averages (2024 season)
export const NFL_LEAGUE_AVGS = {
  pass_yds_allowed:    228,
  rush_yds_allowed:    111,
  rec_yds_allowed_wr:  152,
  rec_yds_allowed_te:  63,
  rec_yds_allowed_rb:  39,
};
